import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from '@/components/templates/header';
import { ProviderLayout } from '@/components/layouts/providers';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface IProps {
  children: React.ReactNode;
}
export default async function RootLayout({ children }: IProps) {
  return (
    <ProviderLayout>
      <html lang="en">
        <body className={inter.className}>
          <div className="min-h-dvh flex flex-col justify-between">
            <Header/>
            <main className="flex-1 p-24">
              {children}
            </main>
            <footer>footer</footer>
          </div>
        </body>
      </html>
    </ProviderLayout>
  );
}
